# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Local Workflow

on:
  workflow_dispatch:
    inputs:
      file_name:
        description: "The name of the file to process"
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm ci
      # - run: npm test

      - name: list files
        run: ls -al

      - name: list current directory
        run: pwd

      - name: TestifyAI Agent
        id: test-action
        uses: khanzzirfan/TestAI-Agent@v0.1.54-alpha.20
        with:
          repo_token: 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
          file_name: App.tsx
        env:
          OPENAI_API_KEY: ${{ env.OPENAI_API_KEY }}
          TAVILY_API_KEY: ${{ env.TAVILY_API_KEY }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          LANGCHAIN_TRACING_V2: true
          LANGCHAIN_ENDPOINT: "https://api.smith.langchain.com"
          LANGCHAIN_PROJECT: "jest-test"
          LANGCHAIN_API_KEY: ${{ env.LANGCHAIN_API_KEY }}
